---
- name: Configure Cron Job to Kill sngrep Process
  hosts: all
  gather_facts: no
  tasks:
    - name: Add cron job to kill sngrep process every 15 minutes
      cron:
        name: "Kill sngrep process"
        minute: "*/15"
        job: "/path/to/kill_sngrep.sh"
